FROM openjdk:8-jdk-alpine

ENTRYPOINT ["/usr/bin/java", "-jar", "/usr/share/hellojavakubernetes/springboot-demo3-0.0.1.jar"]

# Add Maven dependencies
ADD target/springboot-demo3-0.0.1.jar /usr/share/hellojavakubernetes/springboot-demo3-0.0.1.jar